version: '3.8'

services:
  gallery:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - ./apps/gallery/.env
    depends_on:
      - mongo
      - rabbitmq

  listener:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - ./apps/listener/.env
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - '27018:27017'

  rabbitmq:
    image: rabbitmq:management
    ports:
      - '15673:15672'
      - '5673:5672'

volumes:
  mongo-data:
